Data preprocessing
marton-balazs-kovacs/preregistration_evaluation pull request #1
Opened 2020-11-18 19:22 UTC by bencebakos96

Data preprocessing completed.

2020-11-23 14:13 UTC, marton-balazs-kovacs requested changes
Very nice job Bence! I added some suggestions, not because your code was not working, but because I think they will improve the readability and help us in the analysis process.

2020-11-23 14:13 UTC, marton-balazs-kovacs commented on PreregistrationEvaluation_Main_Raw_Processed.Rmd
> +# Recoding response variables to numeric
The data that you are working with is not tidy. By this I mean that you have variables that contain double information e.g. "control_hypothesis" contains the fact that the response is coming from a control group, and the response for the hypothesis question. First, I strongly suggest tidying your data. The "group" variable already contains the information which group a participant belongs to. So we do not need to keep "prereg_hypothesis" and "control_hypothesis" in different variables.

```
tidy_data <- 
  filtered_data %>% 
  # Gather all the columns with "prereg_" or "control_" prefix
  pivot_longer(
    cols = union(contains("prereg_"),contains("control_")),
    names_to = "variable_names",
    values_to = "values"
  ) %>% 
  # Response was forced so all NA values mean that the participant was not member of that group
  # So we can drop them
  drop_na(values) %>% 
  # Delete prefix ad convert character variables to numeric
  mutate(variable_names = str_remove(variable_names, "prereg_|control_"),
         # Because there is a mismatch in the variable names between the control and prereg group
         variable_names = case_when(variable_names == "rmd" ~ "rdm",
                                    TRUE ~ variable_names),
         values = case_when(values == "I do not know" ~ "0",
                            values == "Not applicable" ~ "99",
                            values == "Very Strongly Disagree" ~ "1",
                            values == "Strongly Disagree" ~ "2",
                            values == "Disagree" ~ "3",
                            values == "Neither Agree or Disagree" ~ "4",
                            values == "Agree" ~ "5",
                            values == "Strongly Agree" ~ "6",
                            values == "Very Strongly Agree" ~ "7",
                            TRUE ~ values),
         values = as.integer(str_extract(values, "[0-9]{1,2}"))) %>% 
  # Spread gathered columns to make the datatable tidy
  pivot_wider(
    names_from = variable_names,
    values_from = values
  )
```

2020-11-23 18:15 UTC, bencebakos96 commented on PreregistrationEvaluation_Main_Raw_Processed.Rmd
> +
Very good idea!

2020-11-23 18:18 UTC, bencebakos96 commented on PreregistrationEvaluation_Main_Raw_Processed.Rmd
> +         Progress == 100,
I changed it to `progress == "100"`

2020-11-23 18:20 UTC, bencebakos96 commented on PreregistrationEvaluation_Main_Raw_Processed.Rmd
> +         group == "control" & control_attention == "4
Yes, I was using enter because there was an enter in the text. Now I'll change all enters to "\n". Thanks!

2020-12-01 11:10 UTC, marton-balazs-kovacs approved these changes

2020-12-01 11:11 UTC, merged